In [1]:
import os
import pandas as pd

In [13]:
file_dir = os.getcwd()  + '/data/FPL18-GW0.csv'
df = pd.read_csv(file_dir)

df['5_game_forecast'] = df['GW1Forecast'] + df['GW2Forecast'] + df['GW3Forecast'] +\
                          df['GW4Forecast'] + df['GW5Forecast']
 
df['Cost'] = df['Cost'] / 1000000
gk_df = df[df['PositionsList'] == 'GLK']
def_df = df[df['PositionsList'] == 'DEF']
mid_df = df[df['PositionsList'] == 'MID']
fwd_df = df[df['PositionsList'] == 'FWD']

df.sort_values(by=['5_game_forecast'], ascending=False).head(70)\
    [['FirstName', 'Surname', 'Team', 'Cost', '5_game_forecast']]

     FirstName      Surname Team  Cost  5_game_forecast
370    Mohamed        Salah  LIV  13.0             50.8
407     Raheem     Sterling  MCI  11.0             39.1
104      Kevin    De Bruyne  MCI  10.0             34.9
217      Harry         Kane  TOT  12.5             34.3
269      Riyad       Mahrez  MCI   9.0             32.2
134  Christian      Eriksen  TOT   9.5             28.4
423      Jamie        Vardy  LEI   9.0             27.9
144    Roberto      Firmino  LIV   9.5             27.8
2       Sergio       Aguero  MCI  11.0             27.3
175       Eden       Hazard  CHE  10.5             26.9
105      David       De Gea  MUN   6.0             26.7
21       Cesar  Azpilicueta  CHE   6.5             26.7
128        NaN      Ederson  MCI   5.5             24.6
8       Marcos       Alonso  CHE   6.5             24.6
341       Nick         Pope  BUR   5.0             24.5
398  Heung-Min          Son  TOT   8.5             24.4
328    Nicolas     Otamendi  MCI   6.5             24.2
7     Bamidele         Alli  TOT   9.0             23.8
265     Romelu       Lukaku  MUN  11.0             23.5
137     Lukasz    Fabianski  WHU   4.5             23.0
163     Pascal         Gro?  BHA   7.0             22.4
365     Mathew         Ryan  BHA   4.5             22.3
338     Jordan     Pickford  EVE   5.0             21.4
382    Xherdan      Shaqiri  LIV   7.5             21.3
419    Antonio     Valencia  MUN   6.5             21.2
254       Hugo       Lloris  TOT   5.5             21.2
101        Ben       Davies  TOT   6.0             21.0
431       Kyle       Walker  MCI   6.5             20.7
14       Marko   Arnautovic  WHU   7.0             20.3
260      Jonas        Lossl  HUD   4.5             20.1