### Load fantasy premier league data

In [2]:
import requests
import json
import pandas as pd
import numpy as np
from tqdm import tqdm

In [13]:
def load_json(url):
    response = requests.get(url)
    return json.loads(response.content.decode('utf-8'))


def load_player_gameweek():
    gameweek_dfs = []
    for player_id in tqdm(player_summary_df['id'].unique()):
        url = "https://fantasy.premierleague.com/drf/element-summary/" + str(player_id)
        response = requests.get(url)
        gameweek_data = json.loads(response.content.decode('utf-8'))['history']
        gameweek_dfs.append(pd.DataFrame(gameweek_data))
        
    gameweek_df = pd.concat(gameweek_dfs)
    gameweek_df.to_csv('player_gameweeks.csv')

# df = pd.read_json(load_summa())
# player_summary = load_summary()
# player_summary_df = pd.DataFrame(load_json('https://fantasy.premierleague.com/drf/elements/'))
# player_summary_df.to_csv('player_summaries.csv')

player_summary_df = pd.read_csv('player_summaries.csv')
# load_player_gameweek()
player_gameweek_df = player_gameweek_df.drop(player_gameweek_df.columns[0], axis=1)
player_gameweek_df.head()
player_gameweek_df = pd.read_csv('player_gameweeks.csv')
player_team_df = pd.DataFrame(load_json('https://fantasy.premierleague.com/drf/teams'))
player_team_df.head()

# https://fantasy.premierleague.com/drf/fixtures
fixture_df = pd.DataFrame(load_json('https://fantasy.premierleague.com/drf/fixtures'))
fixture_df.head()

,code,deadline_time,deadline_time_formatted,event,event_day,finished,finished_provisional,id,kickoff_time,kickoff_time_formatted,minutes,provisional_start_time,started,stats,team_a,team_a_difficulty,team_a_score,team_h,team_h_difficulty,team_h_score
0,918893,2017-08-11T17:45:00Z,11 Aug 18:45,1,1,True,True,1,2017-08-11T18:45:00Z,11 Aug 19:45,90,False,True,"[{'goals_scored': {'a': [{'element': 209, 'val...",9,4,3.0,1,3,4.0
1,918901,2017-08-11T17:45:00Z,11 Aug 18:45,1,2,True,True,7,2017-08-12T11:30:00Z,12 Aug 12:30,90,False,True,"[{'goals_scored': {'a': [{'element': 230, 'val...",10,3,3.0,18,4,3.0
2,918895,2017-08-11T17:45:00Z,11 Aug 18:45,1,2,True,True,3,2017-08-12T14:00:00Z,12 Aug 15:00,90,False,True,"[{'goals_scored': {'a': [{'element': 91, 'valu...",4,4,3.0,5,3,2.0
3,918896,2017-08-11T17:45:00Z,11 Aug 18:45,1,2,True,True,4,2017-08-12T14:00:00Z,12 Aug 15:00,90,False,True,"[{'goals_scored': {'a': [{'element': 188, 'val...",8,3,3.0,6,2,0.0
4,918897,2017-08-11T17:45:00Z,11 Aug 18:45,1,2,True,True,5,2017-08-12T14:00:00Z,12 Aug 15:00,90,False,True,"[{'goals_scored': {'a': [], 'h': [{'element': ...",15,3,0.0,7,2,1.0

In [38]:
recent_gameweeks_index = player_gameweek_df['round'].max() - 5
temp_df = player_gameweek_df[(player_gameweek_df['round'] >= recent_gameweeks_index) &
                            (player_gameweek_df['element'] == 255)]
temp_df[['assists','goals_scored','bps','minutes','selected']]

Empty DataFrame
Columns: [assists, goals_scored, bps, minutes, selected]
Index: []